config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'home/about'
  get 'home/career'
  get 'home/connect'
  get "home/download_pdf"
  post "home/contact_form"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contact_form_controller.rb
class ContactFormController < ApplicationController
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def contact_form
    UserMailer.send_email(params).deliver_now
    flash[:alert] = "Message sent successfully. Thank you!"
    redirect_to :root
  end

  def download_pdf
    send_file(
      "#{Rails.root}/app/assets/images/resume.pdf",
      filename: "Simeon_Lam_Resume.pdf",
      type: "application/pdf"
    )
  end

  private

  def contact_params
    params.require(:contact_form).require(:name, :email, :subject, :message)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_contact_form.html.erb
<%= form_with scope: :contact_form, url: home_contact_form_path, method: :post, local: true, class: "container" do |form| %>
  <div class="form-group">
    <div class="row">
      <div class="col">
        <%= form.text_field :name, class: "form-control", placeholder: "Full Name", required: true %>
      </div>

      <div class="col">
        <%= form.email_field :email, class: "form-control", placeholder: "Email Address", required: true %>
      </div>
    </div><br>

    <%= form.text_field :subject, class: "form-control", placeholder: "Subject", required: true %><br>

    <div class="form-group">
      <%= form.text_area :message, class: "form-control",  placeholder: "Message", rows: "8", required: true%>
    </div><br>

    <div class="d-grid gap-2">
      <%= form.submit "Submit", class: "btn btn-success" %>
    </div><br>
<% end %>

app/views/home/about.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>about me</title>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class ="col-3">
          <%= render "layouts/navbar" %>
        </div>

        <div class="col-md-9 home-text">
          <div class="row protest-riot-regular custom-about-2">
            <div class="col-3">
              <h2>about</h2>
            </div>
            <div class="col rectangle custom-about-1">
            </div>
          </div><br></br>

          <div class="row protest-riot-regular">
            <div class="col-7 custom-about-3">
              <h3>
                Hello there! My name is Simeon. 😄<br></br>

                I'm an avid software developer 💻. My passion involves solving practical problems to help users succeed
                in the real world. I enjoy activities involving optimazation and organization. Check out my career tab on the right!
                <br></br>

                Outside of coding, you'll find me watching tons of pro sports, running in my neighborhood 👟, & competing
                in adult basketball leagues. Inside my home, you'll catch me jamming out on my guitar 🎸 or whipping up
                new recipes in the kitchen 🔪. And when I'm not doing any of those things, you'll notice me planning a new
                adventure - whether my next vacation 🏝️, my next whitewater rafting adventure, and or my next
                snowboarding trip 🏂. <br></br> More fun facts below!
              </h3>
            </div>
            <div class="col-1">
            </div>
            <div class="col-1 custom-about-1">
              <%= image_tag("headshot.jpg", class:"headshot")%>
            </div>
          </div>
          <br>

          <div class="row">
            <div class="col rectangle custom-about-3">
            </div>
          </div>
          <br></br><br>

          <div class="row">
            <div class="col-3 custom-about-4 oswald-light" style="text-align: left">
              <h4>
                <b><u>Favorite Sports Franchises</u></b><br><br>
                🏀 San Antonio Spurs<br></br>
                ⚾ Los Angeles Dodgers<br></br>
                🏈 Seattle Seahawks<br></br>
                🏆 USC Trojans<br></br>
              </h4>
            </div>

            <div class="col-3 custom-about-4 oswald-light" style="text-align: center">
              <h4>
                <b><u>Followed Music Artists</u></b><br><br>
                🎵 LE SSERAFIM<br></br>
                🎙️ Jon Bellion<br></br>
                🎹 Jeremy Zucker<br></br>
                🎸 Rise Against<br></br>
              </h4>
            </div>

            <div class="col-3 custom-about-4 oswald-light" style="text-align: center">
              <h4>
                <b><u>My Top Comfort Foods</u></b><br><br>
                🍔 In-n-out Burger<br></br>
                🍣 Otoro/Hamachi Nigiri<br></br>
                😋 Pork Belly Bossam<br></br>
                🍨 Mango Sago<br></br>
              </h4>
            </div>

            <div class="col-3 custom-about-4 oswald-light" style="text-align: right">
              <h4>
                <b><u>Bucketlist: Places to Visit</u></b><br><br>
                📍 Taiwan, Korea, Hong Kong<br></br>
                📍 Korea, Switzerland, Spain<br></br>
                📍 Iceland, Alaska, Vancouver<br></br>
                📍 Yosemite+Zion National Park<br></br>
              </h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/home/career.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>my career</title>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class ="col-3">
          <%= render "layouts/navbar" %>
        </div>

        <div class="col-9 home-text">
          <div class="row protest-riot-regular custom-about-2">
            <div class="col-3">
              <h2>career</h2>
            </div>
            <div class="col rectangle custom-about-1">
            </div>
          </div>

          <section id="cd-timeline" class="cd-container raleway-light">
            <div class="cd-timeline-block">
              <div class="cd-timeline-img cd-picture"></div>
              <div class="cd-timeline-content custom-about-3">
                <h4>University of California, Irvine</h4>
                <div class="timeline-content-info">
                  <span class="timeline-content-info-title">
                    <i class="fa fa-certificate" aria-hidden="true"></i>
                    B.S., Computer Science
                  </span>
                  <span class="timeline-content-info-date">
                    <i class="fa fa-calendar-o" aria-hidden="true"></i>
                    Sep 2016 - Mar 2020
                  </span>
                </div>
                <p>
                  Intro to coding through coursework with an expertise in Information. Learned multiple
                  languages and frameworks while building apps including an iOS Health Recommendation App.
                </p>
                <ul class="content-skills">
                  <li>Python</li>
                  <li>C++</li>
                  <li>PHP</li>
                  <li>HTML</li>
                  <li>CSS</li>
                  <li>Bootstrap</li>
                  <li>Swift</li>
                </ul>
              </div>
            </div>

            <div class="cd-timeline-block">
              <div class="cd-timeline-img cd-picture"></div>
              <div class="cd-timeline-content custom-about-1">
                <h4>Storyblaster Inc.</h4>
                <div class="timeline-content-info">
                  <span class="timeline-content-info-title">
                    <i class="fa fa-certificate" aria-hidden="true"></i>
                    Data / Software Intern
                  </span>
                  <span class="timeline-content-info-date">
                    <i class="fa fa-calendar-o" aria-hidden="true"></i>
                    June 2019 - Aug 2019
                  </span>
                </div>
                <p>
                  First internship in the software industry. Gained valuable hands-on experience with a crowdfunding
                  and audience-building software. Highlights: creating user personas and data analysis patterns.
                </p>
              </div>
            </div>

            <div class="cd-timeline-block">
              <div class="cd-timeline-img cd-picture"></div>
              <div class="cd-timeline-content custom-about-3">
                <h4>Kantata</h4>
                <div class="timeline-content-info">
                  <span class="timeline-content-info-title">
                    <i class="fa fa-certificate" aria-hidden="true"></i>
                    IT Intern
                  </span>
                  <span class="timeline-content-info-date">
                    <i class="fa fa-calendar-o" aria-hidden="true"></i>
                    Sep 2019 - Jun 2021
                  </span>
                </div>
                <p>
                  Internship involving a mix of Information Technology tasks and Integrations Engineering tasks.
                  Help set up software applications as well as physical company devices. Shadowed and paired with
                  senior engineers on multiple platforms.
                </p>
                <ul class="content-skills">
                  <li>Microsoft 365</li>
                  <li>BetterCloud</li>
                </ul>
              </div>
            </div>

            <div class="cd-timeline-block">
              <div class="cd-timeline-img cd-picture"></div>
              <div class="cd-timeline-content custom-about-1">
                <h4>Kantata</h4>
                <div class="timeline-content-info">
                  <span class="timeline-content-info-title">
                    <i class="fa fa-certificate" aria-hidden="true"></i>
                    Software Engineer I
                  </span>
                  <span class="timeline-content-info-date">
                    <i class="fa fa-calendar-o" aria-hidden="true"></i>
                    July 2021 - Dec 2023
                  </span>
                </div>
                <p>
                  Became a full-time junior engineer after demonstrating proficiency as an intern. Developed multiple web
                  applications and leveraged extensive knowledge of APIs. Excelled in optimizing and organizing company repositories.
                </p>
                <ul class="content-skills">
                  <li>Ruby</li>
                  <li>Ruby on Rails</li>
                  <li>PostgreSQL</li>
                  <li>Git</li>
                  <li>Heroku</li>
                  <li>Kubernetes</li>
                  <li>Postman</li>
                </ul>
              </div>
            </div>
          </section>

          <div class="row">
            <div class="col rectangle custom-about-3">
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/home/connect.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>connect w/ me</title>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class ="col-3">
          <%= render "layouts/navbar" %>
        </div>

        <div class="col-9 home-text">
          <div class="row protest-riot-regular custom-about-2">
            <div class="col-3">
              <h2>connect</h2>
            </div>
            <div class="col rectangle custom-about-1">
            </div>
          </div><br></br>

          <div class="row custom-about-3">
            <div class="col">
              <a href="https://www.linkedin.com/in/simeon-j-lam/" class="btn btn-primary" role="button" style="margin-right:30px" target="_blank">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-linkedin" viewBox="0 0 16 16">
                  <path d="M0 1.146C0 .513.526 0 1.175 0h13.65C15.474 0 16 .513 16 1.146v13.708c0 .633-.526 1.146-1.175 1.146H1.175C.526 16 0 15.487 0 14.854zm4.943 12.248V6.169H2.542v7.225zm-1.2-8.212c.837 0 1.358-.554 1.358-1.248-.015-.709-.52-1.248-1.342-1.248S2.4 3.226 2.4 3.934c0 .694.521 1.248 1.327 1.248zm4.908 8.212V9.359c0-.216.016-.432.08-.586.173-.431.568-.878 1.232-.878.869 0 1.216.662 1.216 1.634v3.865h2.401V9.25c0-2.22-1.184-3.252-2.764-3.252-1.274 0-1.845.7-2.165 1.193v.025h-.016l.016-.025V6.169h-2.4c.03.678 0 7.225 0 7.225z"/>
                </svg>
                &nbsp;LinkedIn&nbsp;
              </a>
              <a href="https://github.com/simeon13" class="btn btn-secondary" role="button" style="margin-right:30px" target="_blank">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-github" viewBox="0 0 16 16">
                  <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27s1.36.09 2 .27c1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.01 8.01 0 0 0 16 8c0-4.42-3.58-8-8-8"/>
                </svg>
                &nbsp;GitHub&nbsp;
              </a>

              <a href="download_pdf" download="resume.pdf" class="btn btn-light" role="button" style="margin-right:30px" target="_blank">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-download" viewBox="0 0 16 16">
                  <path d="M.5 9.9a.5.5 0 0 1 .5.5v2.5a1 1 0 0 0 1 1h12a1 1 0 0 0 1-1v-2.5a.5.5 0 0 1 1 0v2.5a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2v-2.5a.5.5 0 0 1 .5-.5"/>
                  <path d="M7.646 11.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 10.293V1.5a.5.5 0 0 0-1 0v8.793L5.354 8.146a.5.5 0 1 0-.708.708z"/>
                </svg>
                &nbsp;Resumé&nbsp;
              </a>
            </div>
          </div><br><hr></br>

          <div class="row acme-regular row custom-about-1">
            <h3>Question + Comments + Inquiries</h3><br></br>
            <%=render :partial => "contact_form"%>
          </div>

          <div class="row">
            <div class="col rectangle custom-about-3">
            </div>
          </div>
          <br></br><br>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/home/index.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>simeon lam</title>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <div class ="col-3">
          <%= render "layouts/navbar" %>
        </div>
        <div class="col-9 home-text">
          <% flash.each do |type, msg| %>
            <div class="alert alert-info">
              <%= msg %>
            </div><br>
          <% end %>
          <div class="wrapper">
            <div class="triangle top-layer">
            </div>

            <div class="bottom-layer">
              <div class="protest-riot-regular custom-home-2">
                <h2>hello, i'm simeon lam...</h2>
              </div><br>
              <div class="permanent-marker-regular custom-home-1">
                <h1>a software engineer,</h1>
                <h1>innovator & sports fanatic</h1>
              </div><br></br>
              <div class="protest-riot-regular custom-home-3">
                <h3>I have 2.5 years of experience as a SWE in the SaaS Cloud Industry.</h3><br>
                <h3>
                  Above all else, my top values are <u>collaboration</u>, <u>empathy</u>, and <u>growth</u>.
                  I am committed to becoming the best version of myself in both my professional and personal life.
                </h3><br>
                <h3><u>"You miss 100 percent of the shots you don't take."</u></h3>
              </div>
            </div>
          </div><br></br><br></br><br></br>

          <div class="pacman">
            <div class="pacman-top"></div>
            <div class="pacman-bottom"></div>
            <div class="feed"></div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light">
  <div class="container-fluid">
    <a class="navbar-brand permanent-marker-regular" href="/home/index">&lt; SL &gt; </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active protest-riot-regular" aria-current="page" href="/home/about">about</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active protest-riot-regular" href="/home/career">career</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active protest-riot-regular" href="/home/connect">connect</a>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= favicon_link_tag asset_path('cloud.png') %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&family=Protest+Riot&family=Lato&family=Oswald:wght@300&family=Acme&family=Raleway:ital,wght@0,300;1,300&display=swap" rel="stylesheet">
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>

    <%= yield %>
  </body>
</html>